### PR TITLE
fix: 2% blocks missed after sync aggregate addition

### LINKED ISSUE #1292: SyncAggregate: 2% of invalid Signatures on block proposals where we are most of the validators.
#1288 introduced sync aggregates. On setups where we are almos every validator in the main spec, we loose near 2% of blocks due to invalid signatures, here is a debug example, apparently aggregation bits are correct so this may be a deeper issue.

```elixir
# Subnet 0 the only one with less than 128 validators
"For subnet: 0 validators = [16, 54, 18, 19, 42, 27, 49, 62, 56, 35, 24, 53, 50, 36, 21, 52, 22, 17, 55, 58, 60, 14, 15, 20, 41, 40, 59, 13, 38, 51, 28, 34, 25, 32, 37, 31, 46, 63, 26, 57, 48, 45, 39, 43, 30, 61, 47, 29, 12, 23, 44, 19]"
validators added to the list: [34, 51, -1, 35, 57, -1, 47, 21, -1, -1, 31, 48, 39, 62, 60, -1, 
61, -1, 13, 28, 26, 44, 22, 18, 41, 43, -1, 32, 63, 12, 54, 38, -1, 45, 24, 58, -1, 56, 15, 53,
 37, 17, 27, 40, 19, -1, 55, -1, 46, -1, 59, 52, 14, 20, 30, 29, 
 36, 16, 23, 49, 42, 25, 50, -1, 34, 51, -1, 35, 57, -1, 47, 21, -1, -1, 31, 48, 39, 62, 60, -1,
 61, -1, 13, 28, 26, 44, 22, 18, 41, 43, -1, 32, 63, 12, 54, 38,
 -1, 45, 24, 58, -1, 56, 15, 53, 37, 17, 27, 40, 19, -1, 55, -1, 46, -1, 59, 52, 14, 20, 30, 29,
 36, 16, 23, 49, 42, 25, 50, -1]
aggregation bits: "01111111 11111101 01011111 11101110 11111011 11111101 01111100 11011011 01111111 11111101 01011111 11101110 11111011 11111101 01111100 11011011"

# Sync aggregate bits
sync_committee_bits: "
  11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111
  11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111
  11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111
  01111111 11111101 01011111 11101110 11111011 11111101 01111100 11011011 01111111 11111101 01011111 11101110 11111011 11111101 01111100 11011011"

# Validators from which this siganture was validated given the aggreegation bits
validated_indexes: [34, 51, -11, 35, 57, -9, 47, 21, -4, 0, 31, 48, 39, 62, 60, -1, 61, -8, 13, 28,
  26, 44, 22, 18, 41, 43, -5, 32, 63, 12, 54, 38, -3, 45, 24, 58, -7, 56, 15, 53,
  37, 17, 27, 40, 19, -2, 55, -6, 46, -33, 59, 52, 14, 20, 30, 29, 36, 16, 23,
  49, 42, 25, 50, -10, 34, 51, -11, 35, 57, -9, 47, 21, -4, 0, 31, 48, 39, 62,
  60, -1, 61, -8, 13, 28, 26, 44, 22, 18, 41, 43, -5, 32, 63, 12, 54, 38, -3, 45,
  24, 58, -7, 56, 15, 53, 37, 17, 27, 40, 19, -2, 55, -6, 46, -33, 59, 52, 14,
  20, 30, 29, 36, 16, 23, 49, 42, 25, 50, -10, 34, 51, 11, 35, 57, 9, 47, 21, 4,
  0, 31, 48, 39, 62, 60, 1, 61, 8, 13, 28, 26, 44, 22, 18, 41, 43, 5, 32, 63, 12,
  54, 38, 3, 45, 24, 58, 7, 56, 15, 53, 37, 17, 27, 40, 19, 2, 55, 6, 46, 33, 59,
  52, 14, 20, 30, 29, 36, 16, 23, 49, 42, 25, 50, 10, 34, 51, 11, 35, 57, 9, 47,
  21, 4, 0, 31, 48, 39, 62, 60, 1, 61, 8, 13, 28, 26, 44, 22, 18, 41, 43, 5, 32,
  63, 12, 54, 38, 3, 45, 24, 58, 7, 56, 15, 53, 37, 17, 27, 40, 19, 2, 55, 6, 46,
  33, 59, 52, 14, 20, 30, 29, 36, 16, 23, 49, 42, 25, 50, 10, 34, 51, 11, 35, 57,
  9, 47, 21, 4, 0, 31, 48, 39, 62, 60, 1, 61, 8, 13, 28, 26, 44, 22, 18, 41, 43,
  5, 32, 63, 12, 54, 38, 3, 45, 24, 58, 7, 56, 15, 53, 37, 17, 27, 40, 19, 2, 55,
  6, 46, 33, 59, 52, 14, 20, 30, 29, 36, 16, 23, 49, 42, 25, 50, 10, 34, 51, 11,
  35, 57, 9, 47, 21, 4, 0, 31, 48, 39, 62, 60, 1, 61, 8, 13, 28, 26, 44, 22, 18,
  41, 43, 5, 32, 63, 12, 54, 38, 3, 45, 24, 58, 7, 56, 15, 53, 37, 17, 27, 40,
  19, 2, 55, 6, 46, 33, 59, 52, 14, 20, 30, 29, 36, 16, 23, 49, 42, 25, 50, 10,
  34, 51, 11, 35, 57, 9, 47, 21, 4, 0, 31, 48, 39, 62, 60, 1, 61, 8, 13, 28, 26,
  44, 22, 18, 41, 43, 5, 32, 63, 12, 54, 38, 3, 45, 24, 58, 7, 56, 15, 53, 37,
  17, 27, 40, 19, 2, 55, 6, 46, 33, 59, 52, 14, 20, 30, 29, 36, 16, 23, 49, 42,
  25, 50, 10, 34, 51, 11, 35, 57, 9, 47, 21, 4, 0, 31, 48, 39, 62, 60, 1, 61, 8,
  13, 28, 26, 44, 22, 18, 41, 43, 5, 32, 63, 12, 54, 38, 3, 45, 24, 58, 7, 56,
  15, 53, 37, 17, 27, 40, 19, 2, 55, 6, 46, 33, 59, 52, 14, 20, 30, 29, 36, 16,
  23, 49, 42, 25, 50, 10]

# Comparision where everything looks correct....

agg:                     11011011,                               00111110                           10111111                            11011111        <-  11111011 11111101 01111100 11011011
subnet_check:            34, 51, -1, 35, 57, -1, 47, 21          -1, -1, 31, 48, 39, 62, 60, -1     61, -1, 13, 28, 26, 44, 22, 18      41, 43, -1, 32, 63, 12, 54, 38
validated_participants:  34, 51, -11, 35, 57, -9, 47, 21,        -4, -0, 31, 48, 39, 62, 60, -1,    61, -8, 13, 28, 26, 44, 22, 18,     41, 43, -5, 32, 63, 12, 54, 38,

agg:                     01110111                                11111010                           10111111                            11111110                <-  01111111 11111101 01011111 11101110
subnet_check:            -1, 45, 24, 58, -1, 56, 15, 53          37, 17, 27, 40, 19, -1, 55, -1     46, -1, 59, 52, 14, 20, 30, 29      36, 16, 23, 49, 42, 25, 50, -1
validated_participants:  -3, 45, 24, 58, -7, 56, 15, 53,         37, 17, 27, 40, 19, -2, 55, -6,    46, -33, 59, 52, 14, 20, 30, 29,    36, 16, 23, 49, 42, 25, 50, -10, 

# The following 8 bytes are the same as before
# 34, 51, -11, 35, 57, -9, 47, 21,        -4, -0, 31, 48, 39, 62, 60, -1,     61, -8, 13, 28, 26, 44, 22, 18,     41, 43, -5, 32, 63, 12, 54, 38, 
# -3, 45, 24, 58, -7, 56, 15, 53,         37, 17, 27, 40, 19, -2, 55, -6,     46, -33, 59, 52, 14, 20, 30, 29,    36, 16, 23, 49, 42, 25, 50, -10, 
```

### PR DESCRIPTION
**Pull request by rodrigo-o**
**Motivation**

Fixing 2% block missed when proposing on 32 * n + 1 slot.

**Description**

This PR fix the issue related to the Invalid signature error that we got on those particular slots. The problem is related to the parent root, we lacked a filter of contributions that doesn't match our parent root. This was happening at epoch boundaries because that's where we get a delay in the proposal and the second third kicks in before the notify head, which publish messages of the previous root, and make the aggregate become 0.

Resolves #1292

### CODE REVIEW

**Comment by rodrigo-o** [comment]
Now slot 33 is working, but shows 0 because of the delayed 32.

image

File: lib/lambda_ethereum_consensus/validator/duties.ex [hunk 1]
```diff
@@ -71,6 +71,9 @@ defmodule LambdaEthereumConsensus.Validator.Duties do
           ValidatorSet.validators()
         ) :: duties()
   def compute_duties_for_epochs(duties_map, epochs_and_start_slots, head_root, validators) do
+    # TODO: This function needs to be measured and optimized if possible, the main point to look
+    # at is the beacon fetch and sync committees computation. Also this could be done asynchronusly
+    # given that except for the first tame it always calculat 1 epoch ahead of time.
```
Comment (rodrigo-o) [inline lib/lambda_ethereum_consensus/validator/duties.ex:76]: Some information regarding this. The time consumption of sync_committees (which reached 4 seconds on one of my kurtosis tests) is related to the way aggregators are calculated. It has a couple of things very different than attestations which explain why this is costly:
- Attestations are done on one slot per epoch per validator, this is tied to the committee, in sync committees instead, every validator publish in every slot of every epoch during the period of the committee.
- Aggregation is calculated on a per slot basis (we need to compute a signature using the slot) both in attestations and in sync committees, the caveat with sync committees is that they can be aggregators of any slot, which in attestations can only happen once per epoch and here this needs to be checked for the 32 slots.
- This is also calculates for every subcommittee, which in kurtosis main spec every subcommitte is completely repeated due to the low amount of validators (in the test we normally run with less than 120 validators).
- Given all this, for 60 validators (the test I was seeing the 4 seconds delay) we have to calculate proofs for every subcommitte (4) for every slot (32). The proof calculation cost approximately 0.5 ms. so:
  - 60 * 32 * 4 * 0.5 = 3840ms (aprox. 4 seconds)
  
This comment could be removed because:
- If this was an issue, there is not so much room for improvement in the function, but this could be computed asynchronously given that it calculate the next epoch duties ahead of time. This could even be moved some slot further into the new epoch to avoid colliding with the epoch transition.
- In Mainnet this wont be a problem, because having just one validator in a particular period of a sync committee is the norm, more than one in the same period would be statistically improbable. For example, in a test with more participants (10 nodes of 128 validators each and us with 60), the time for computing this was decreased to something near half a second. In a real scenario this will be near a couple of milliseconds.

Comment (Arkenan) [reply lib/lambda_ethereum_consensus/validator/duties.ex:76]: Thanks for the deep dive and the notes. It's pretty clear. I've created the issue #1299 to discuss this for a different PR if needed at all. I suggest adding the issue number to the TODO (all TODOs should refer to an issue IMO).

**Review by Arkenan — APPROVED** [review]
Thanks Rodri! Awesome PR.
