### PR TITLE
fix: errors "mismatched aggregation bits length" and "invalid signature"

### LINKED ISSUE #506: Valid blocks rejected because of "invalid signature"
Other errors:

```
[error] [Fork choice] Failed to add block 7922209 to the store: Mismatched aggregation bits length
```

### PR DESCRIPTION
**Pull request by MegaRedHand**
Closes #506

Adds fixes and refactors some code. The first issue was fixed by 008eb194b52febd71c86edcf6d58804279c45013, and the second one by 87fc797a0ab0fe48cbb5e2567eb50cf8fd01ecba.

We still need to optimize `process_attestation` to make the test pass in a reasonable amount of time.

### CODE REVIEW

File: lib/lambda_ethereum_consensus/state_transition/operations.ex [hunk 1]
```diff
@@ -835,41 +814,74 @@ defmodule LambdaEthereumConsensus.StateTransition.Operations do
...
-      acc <> Integer.to_string(byte, 2)
-    end)
-    |> String.length()
+  defp length_of_bitlist(bitlist) when is_binary(bitlist) do
+    bit_size = bit_size(bitlist)
+    <<_::size(bit_size - 8), last_byte>> = bitlist
+    bit_size - leading_zeros(<<last_byte>>) - 1
   end
 
+  defp leading_zeros(<<1::1, _::7>>), do: 0
```
Comment (mpaulucci) [inline lib/lambda_ethereum_consensus/state_transition/operations.ex:875]: maybe move to Utils.BitVector?

**Review by mpaulucci — APPROVED** [review]

File: lib/lambda_ethereum_consensus/state_transition/operations.ex (hunk 1 above)
Comment (MegaRedHand) [reply lib/lambda_ethereum_consensus/state_transition/operations.ex:875]: It's kind of unrelated. I was gonna move the whole "compute bitlist's length" function to a new `Utils.BitList` module, but I think it's better to tackle that in a future refactor.
