### PR TITLE
fix: block sync hangs on initial node start

### LINKED ISSUE #1308: The block sync sometimes hangs and need to restart the node (Sepolia long run)
This was reproduced a couple of times in Sepolia, when the node is running, specially on node startup. Here are some logs, they don't show a lot but the thing is the node keeps waiting there without doing anything more, I will assume this has to do with peer discovery, but we need to check if thats the case:

```
INFO 17:43:40.228 [Optimistic sync] Performing optimistic sync between slots 5963489 and 5963618, for a total of 130 slots. 
INFO 17:43:40.228 [Optimistic sync] Sending request for slots 5963489 to 5963504 (request size = 16). 
INFO 17:43:40.228 [Optimistic sync] Sending request for slots 5963505 to 5963520 (request size = 16). 
INFO 17:43:40.228 [Optimistic sync] Sending request for slots 5963521 to 5963536 (request size = 16). 
INFO 17:43:40.228 [Optimistic sync] Sending request for slots 5963537 to 5963552 (request size = 16). 
INFO 17:43:40.229 [Optimistic sync] Sending request for slots 5963553 to 5963568 (request size = 16). 
INFO 17:43:40.229 [Optimistic sync] Sending request for slots 5963569 to 5963584 (request size = 16). 
INFO 17:43:40.229 [Optimistic sync] Sending request for slots 5963585 to 5963600 (request size = 16). 
INFO 17:43:40.229 [Optimistic sync] Sending request for slots 5963601 to 5963616 (request size = 16). 
INFO 17:43:40.229 [Optimistic sync] Sending request for slots 5963617 to 5963618 (request size = 2). 
INFO 17:43:40.229 [Optimistic Sync] Blocks remaining: 130 
```

### LINKED ISSUE #1309: Root not found in tree error hangs the node (Sepolia long run)
This is something that could happen along the node executions but is easily reproducible on the initial setup. After the initial sync and some time running (a couple of minutes) an initial pruning kicks in and for some reason it generates a slot in the future error, here is an example log:

```
INFO 17:43:12.001 [StateDb] Pruning started. slot=5963552
INFO 17:43:12.001 [BlobDb] Pruning started. slot=5832480
INFO 17:43:12.001 [BlockDb] Pruning started. slot=5963552
INFO 17:43:12.001 [BlobDb] Pruning finished. 0 blobs removed. 
INFO 17:43:12.003 [Libp2p] Slot transition slot=5963616
INFO 17:43:12.009 [BlockDb] Pruning finished. 52 blocks removed. 
INFO 17:43:12.019 [StateDb] Pruning finished. 52 states removed. 
INFO 17:43:12.684 [Gossip] Block received, block.slot: 5963616. 
INFO 17:43:24.002 [Libp2p] Slot transition slot=5963617
INFO 17:43:24.216 [Gossip] Block received, block.slot: 5963617. 
INFO 17:43:29.977 [Fork choice] Adding new block slot=5963613 root=0x3de..fc05
INFO 17:43:30.204 [Fork choice] Block processed. Recomputing head. 
ERROR 17:43:30.204 GenServer LambdaEthereumConsensus.Libp2pPort terminating
** (RuntimeError) Parent 14C35B27D611342466C990ABE85147AFCDA13DBE2D5C05C4B3155309CF94FFFD not found in tree
    (lambda_ethereum_consensus 0.1.0) lib/lambda_ethereum_consensus/fork_choice/simple_tree.ex:84: LambdaEthereumConsensus.ForkChoice.Simple.Tree.get_children!/2
    (lambda_ethereum_consensus 0.1.0) lib/types/store.ex:147: Types.Store.get_children/2
    (lambda_ethereum_consensus 0.1.0) lib/lambda_ethereum_consensus/fork_choice/head.ex:90: LambdaEthereumConsensus.ForkChoice.Head.filter_block_tree/4
    (lambda_ethereum_consensus 0.1.0) lib/lambda_ethereum_consensus/fork_choice/head.ex:85: LambdaEthereumConsensus.ForkChoice.Head.get_filtered_block_tree/1
    (lambda_ethereum_consensus 0.1.0) lib/lambda_ethereum_consensus/fork_choice/head.ex:14: LambdaEthereumConsensus.ForkChoice.Head.get_head/1
    (lambda_ethereum_consensus 0.1.0) lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex:269: LambdaEthereumConsensus.ForkChoice.recompute_head/1
    (lambda_ethereum_consensus 0.1.0) lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex:62: anonymous fn/1 in LambdaEthereumConsensus.ForkChoice.on_block/2
    (telemetry 1.3.0) /home/admin/lambda_ethereum_consensus/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
Last message: {#Port<0.16>, {:data, <<50, 145, 166, 1, 10, 36, 55, 100, 49, 52, 49, 57, 53, 49, 45, 97, 100, 56, 50, 45, 52, 50, 101, 102, 45, 97, 102, 102, 101, 45, 48, 57, 102, 54, 50, 55, 101, 97, 57, 56, 102, 101, 16, 1, 26, 229, ...>>}} 
INFO 17:43:30.227 [Optimistic Sync] Waiting 10.0 seconds to discover some peers before requesting blocks. 
INFO 17:43:30.227 [Fork choice] Adding new block slot=5963613 root=0x3de..fc05
ERROR 17:43:30.280 [Fork choice] Failed to add block: block is from the future slot=5963613 root=0x3de..fc05
ERROR 17:43:30.280 [PendingBlocks] Saving block as invalid block is from the future slot=5963613 root=0x3de..fc05
INFO 17:43:36.001 [Libp2p] Slot transition slot=5963618
INFO 17:43:40.228 [Optimistic sync] Performing optimistic sync between slots 5963489 and 5963618, for a total of 130 slots. 
```

This happens to kick in sync again and and may trigger #1308 issue.

### PR DESCRIPTION
**Pull request by rodrigo-o**
**Motivation**

This PR tries to fix the hanging that happens often in Sepolia, specially at the first Sync.

**Description**

The issue was related to peer scoring/penalizing, right now we had a naive implementation where penalization immediatly removed a peer. I made some small changes to have a better scenario, specially on Sepolia where this issue happen the most. Ultimately what made the node hang was getting out of peers and ending in a sleep cycle that never released LibP2P to handle incoming new peers. The points tackled are:
- Add a couple of seconds more before the sync starts
- Implement a really simple penalizing algorithm that just decrease the score of a peer every time it's penalized
- Implement a naive scoring algorithm that takes of a small pool of good-scored peers

This PR is enough for most situations, it will be rare to end up with an empty peerbook, and in case it happens we'll see an error quickly, failing instead of leaving us waiting. There are some follow-ups but are lower in priority than for example #1309:
- I created #1317 for tackling the root cause of this issue in depth, we need to give LibP2P control again instead of sleeping and make sure that getting a peer is handled properly.
- We need to keep an eye at the current poor-man's peer scoring implementation

Resolves #1308

### CODE REVIEW

**Comment by rodrigo-o** [comment]
After removing the pruning from the on_tick this issue now appeared without the pruning:

```
INFO 20:41:24.422 [Gossip] Block received, block.slot: 6000507. 
INFO 20:41:26.883 [Fork choice] Adding new block slot=6000506 root=0x735..0ab3
INFO 20:41:27.077 [Fork choice] Block processed. Recomputing head. 
INFO 20:41:27.266 [Fork choice] Added new block slot=6000506 root=0x735..0ab3
INFO 20:41:27.266 [Fork choice] Adding new block slot=6000507 root=0xbf0..eb92
INFO 20:41:27.442 [Fork choice] Block processed. Recomputing head. 
INFO 20:41:27.636 [Fork choice] Added new block slot=6000507 root=0xbf0..eb92
INFO 20:41:36.004 [Libp2p] Slot transition slot=6000508
INFO 20:41:36.361 [Gossip] Block received, block.slot: 6000508. 
INFO 20:41:36.408 [Fork choice] Adding new block slot=6000508 root=0x0af..57d1
INFO 20:41:36.600 [Fork choice] Block processed. Recomputing head. 
INFO 20:41:36.809 [Fork choice] Added new block slot=6000508 root=0x0af..57d1
INFO 20:41:48.006 [Libp2p] Slot transition slot=6000509
INFO 20:41:48.501 [Gossip] Block received, block.slot: 6000509. 
INFO 20:41:48.535 [Fork choice] Adding new block slot=6000509 root=0x6bd..dc0b
INFO 20:41:48.741 [Fork choice] Block processed. Recomputing head. 
INFO 20:41:48.978 [Fork choice] Added new block slot=6000509 root=0x6bd..dc0b
INFO 20:42:00.016 [Libp2p] Slot transition slot=6000510
INFO 20:42:01.233 [Gossip] Block received, block.slot: 6000510. 
INFO 20:42:01.430 [Fork choice] Adding new block slot=6000510 root=0x6a0..f76f
INFO 20:42:01.639 [Fork choice] Block processed. Recomputing head. 
INFO 20:42:01.820 [Fork choice] Added new block slot=6000510 root=0x6a0..f76f
INFO 20:42:09.024 [Fork choice] Adding new block slot=6000510 root=0x6a0..f76f
INFO 20:42:09.222 [Fork choice] Block processed. Recomputing head. 
INFO 20:42:09.383 [Fork choice] Added new block slot=6000510 root=0x6a0..f76f
INFO 20:42:12.003 [Libp2p] Slot transition slot=6000511
INFO 20:42:12.536 [Gossip] Block received, block.slot: 6000511. 
INFO 20:42:12.546 [Fork choice] Adding new block slot=6000511 root=0x38c..6194
INFO 20:42:12.754 [Fork choice] Block processed. Recomputing head. 
INFO 20:42:12.980 [Fork choice] Added new block slot=6000511 root=0x38c..6194
INFO 20:42:24.005 [Libp2p] Slot transition slot=6000512
INFO 20:42:24.374 [Gossip] Block received, block.slot: 6000512. 
INFO 20:42:25.671 [Fork choice] Adding new block slot=6000512 root=0x276..0cd6
INFO 20:42:26.004 [Fork choice] Block processed. Recomputing head. 
ERROR 20:42:26.007 GenServer LambdaEthereumConsensus.Libp2pPort terminating
** (RuntimeError) Parent 88058BB979CDC75A5E3B419AE09F9D0FA802699BF9C0E008D86CA8C839F2C695 not found in tree
    (lambda_ethereum_consensus 0.1.0) lib/lambda_ethereum_consensus/fork_choice/simple_tree.ex:84: LambdaEthereumConsensus.ForkChoice.Simple.Tree.get_children!/2
    (lambda_ethereum_consensus 0.1.0) lib/types/store.ex:148: Types.Store.get_children/2
    (lambda_ethereum_consensus 0.1.0) lib/lambda_ethereum_consensus/fork_choice/head.ex:90: LambdaEthereumConsensus.ForkChoice.Head.filter_block_tree/4
    (lambda_ethereum_consensus 0.1.0) lib/lambda_ethereum_consensus/fork_choice/head.ex:85: LambdaEthereumConsensus.ForkChoice.Head.get_filtered_block_tree/1
    (lambda_ethereum_consensus 0.1.0) lib/lambda_ethereum_consensus/fork_choice/head.ex:14: LambdaEthereumConsensus.ForkChoice.Head.get_head/1
    (lambda_ethereum_consensus 0.1.0) lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex:272: LambdaEthereumConsensus.ForkChoice.recompute_head/1
    (lambda_ethereum_consensus 0.1.0) lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex:62: anonymous fn/1 in LambdaEthereumConsensus.ForkChoice.on_block/2
    (telemetry 1.3.0) /Users/roliveri/prog/elixir/consensus/lambda_ethereum_consensus/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
Last message: {#Port<0.19>, {:data, <<10, 174, 175, 7, 10, 40, 47, 101, 116, 104, 50, 47, 100, 51, 49, 102, 54, 49, 57, 49, 47, 98, 108, 111, 98, 95, 115, 105, 100, 101, 99, 97, 114, 95, 51, 47, 115, 115, 122, 95, 115, 110, 97, 112, 112, 121, ...>>}} 
INFO 20:42:26.022 [Optimistic Sync] Waiting 10.0 seconds to discover some peers before requesting blocks. 
INFO 20:42:26.022 [Fork choice] Adding new block slot=6000512 root=0x276..0cd6
ERROR 20:42:26.071 [Fork choice] Failed to add block: block is from the future slot=6000512 root=0x276..0cd6
ERROR 20:42:26.072 [PendingBlocks] Saving block as invalid block is from the future slot=6000512 root=0x276..0cd6
INFO 20:42:36.006 [Libp2p] Slot transition slot=6000513
```

File: lib/lambda_ethereum_consensus/p2p/peerbook.ex [hunk 1]
```diff
@@ -81,14 +111,10 @@ defmodule LambdaEthereumConsensus.P2P.Peerbook do
   defp prune() do
```
Comment (rodrigo-o) [inline lib/lambda_ethereum_consensus/p2p/peerbook.ex:111]: We can do something similar to the peer selection in the pruning and just prune the lower score ones but is probably something to tackle in a PR that focus on the peer-scoring algorithm.

**Review by Arkenan — APPROVED** [review]
LGTM.
