### PR TITLE
fix: recompute head was taking more than 20s in mainnet

### LINKED ISSUE #1381: Recompute head takes 20+ seconds in mainnet
This executes every slot but shouldn't be a pretty extensive operation in most case where there are no forks. This is probably a bug

### PR DESCRIPTION
**Pull request by rodrigo-o**
**Motivation**

Running the node for more than an epoch and just after block processing, 20+ seconds were taken before finishing the fork choice step, which made it impossible to execute sequentially inside the slot range (12s)

**Description**

After extensive debugging, the issue was found in the recompute head calculation, specially in the repeatedly call of get_weight where it wasn't really needed (outside of forks). The solution was taking into account this cases and stop calculating get_weight when encountered. 

Resolves #1381

### CODE REVIEW

**Comment by rodrigo-o** [comment]
Is possible that #1321 stop happening as usually as today, get_weight was called every time before, now is just used on a fork choice as it should.

File: lib/lambda_ethereum_consensus/fork_choice/head.ex [hunk 1]
```diff
@@ -11,27 +11,38 @@ defmodule LambdaEthereumConsensus.ForkChoice.Head do
...
-    Stream.cycle([nil])
-    |> Enum.reduce_while(head, fn nil, head ->
-      blocks
-      |> Stream.filter(fn {_, block} -> block.parent_root == head end)
-      |> Stream.map(fn {root, _} -> root end)
-      # Ties broken by favoring block with lexicographically higher root
-      |> Enum.sort(:desc)
-      |> then(fn
-        [] -> {:halt, head}
-        c -> {:cont, Enum.max_by(c, &get_weight(store, &1, justified_state))}
```
Comment (rodrigo-o) [inline lib/lambda_ethereum_consensus/fork_choice/head.ex:31]: As we discussed with @ElFantasma this could have been just 1 line change like:

```elixir
  |> then(fn
    [] -> {:halt, head}
    [single_child] -> {:cont, single_child}
    c -> {:cont, Enum.max_by(c, &get_weight(store, &1, justified_state))}
```

most of the changes are just for readability

**Review by ElFantasma — APPROVED** [review]
It looks good to me.
I also think that your version has improved readability but I'd like some of the code authors' to take a look on the style change, to ensure they agree on that. Maybe @mpaulucci or @Arkenan ?

**Comment by rodrigo-o** [comment]
**Before:**
```
INFO 19:55:02.101 [Fork choice] Adding new block slot=10997567 root=0x441..ea20
INFO 19:55:16.618 [Fork choice] Block processed. Recomputing head. 
INFO 19:55:45.444 [Fork choice] Added new block slot=10997567 root=0x441..ea20
INFO 19:55:45.448 [Fork choice] Recomputed head slot=10997567 root=0x441..ea20
INFO 19:55:45.448 [Fork choice] Block processing time: 14.519s | Recompute head time: 28.49s 

INFO 19:55:45.452 [Fork choice] Adding new block slot=10997568 root=0x562..2598
INFO 19:57:56.985 [Fork choice] Block processed. Recomputing head. 
INFO 19:58:28.116 [Fork choice] Added new block slot=10997568 root=0x562..2598
INFO 19:58:28.118 [Fork choice] Recomputed head slot=10997568 root=0x562..2598
INFO 19:58:28.118 [Fork choice] Block processing time: 131.536s | Recompute head time: 30.785s 
```

**After:**
```
INFO 19:30:26.903 [Fork choice] Adding new block slot=10997406 root=0x172..b1a8
INFO 19:30:42.722 [Fork choice] Block processed. Recomputing head. 
INFO 19:30:43.274 [Fork choice] Added new block slot=10997406 root=0x172..b1a8
INFO 19:30:43.274 [Fork choice] Recomputed head slot=10997406 root=0x172..b1a8
INFO 19:30:43.274 [Fork choice] Block processing time: 15.819s | Recompute head time: 0.176s 

INFO 19:30:43.276 [Fork choice] Adding new block slot=10997407 root=0xe95..672d
INFO 19:30:59.552 [Fork choice] Block processed. Recomputing head. 
INFO 19:31:00.352 [Fork choice] Added new block slot=10997407 root=0xe95..672d
INFO 19:31:00.353 [Fork choice] Recomputed head slot=10997407 root=0xe95..672d
INFO 19:31:00.353 [Fork choice] Block processing time: 16.276s | Recompute head time: 0.288s
```

**Review by mpaulucci — APPROVED** [review]
LGTM
