### PR TITLE
fix: ensure module is loaded before encoding/decoding

### LINKED ISSUE #217: ArgumentError: `1st argument: not an integer`
Every now and then, we get an error message like this:

```
11:11:37.580 [error] ** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an integer

    (stdlib 4.3) :binary.encode_unsigned(<<126, 48, 193, 62, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, :little)
    (lambda_ethereum_consensus 0.1.0) lib/ssz.ex:73: Ssz.encode_u256/1
    (elixir 1.15.4) lib/map.ex:916: Map.update!/3
    (lambda_ethereum_consensus 0.1.0) lib/ssz.ex:49: anonymous fn/1 in Ssz.encode/1
    (elixir 1.15.4) lib/enum.ex:1701: anonymous fn/3 in Enum.map/2
    (stdlib 4.3) maps.erl:411: :maps.fold_1/3
    (elixir 1.15.4) lib/enum.ex:2522: Enum.map/2
    (lambda_ethereum_consensus 0.1.0) lib/ssz.ex:49: Ssz.encode/1
```

### PR DESCRIPTION
**Pull request by MegaRedHand**
Closes #217

From the `Kernel.function_exported?` documentation:

> Returns true if module **is loaded** and contains a public function with the given arity, otherwise false.

Since the module wasn't loaded at first, we weren't encoding U256s properly.

### CODE REVIEW

File: lib/ssz.ex [hunk 1]
```diff
@@ -84,6 +84,8 @@ defmodule Ssz do
 
   # Ssz types can have special decoding rules defined in their optional encode/1 function,
   defp encode(%name{} = struct) do
+    Code.ensure_loaded!(name)
```
Comment (Arkenan) [inline lib/ssz.ex:87]: As we always use function_exported paired with ensure_loaded, I'd create a small function to do both:

```elixir
def exported?(module, function, arity) do
  Code.ensure_loaded!(name)
  function_exported?(name, :encode, 1)
end
```

and then call that one directly.

**Review by Arkenan — APPROVED** [review]
Approved with small comment.

File: lib/ssz.ex (hunk 1 above)
Comment (MegaRedHand) [reply lib/ssz.ex:87]: Good idea!
